AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  app
  Sample SAM Template for app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  CormieDotComFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Events:
        SimpleApp:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
    Metadata:
      DockerTag: nodejs14.x-v1
      DockerContext: ./cormie-com-app
      Dockerfile: Dockerfile

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SimpleAppApi:
    Description: "API Gateway endpoint URL for Prod stage for cormie.com function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/cormie-com/"
  CormieDotComFunction:
    Description: "Cormie.com Lambda Function ARN"
    Value: !GetAtt CormieDotComFunction.Arn
  CormieDotComFunctionIamRole:
    Description: "Implicit IAM Role created for Cormie.com function"
    Value: !GetAtt CormieDotComFunctionRole.Arn
